### ISSUE TITLE
.cer file generate but not with the .cer extension

### ISSUE THREAD

**Issue by prbreezy** [J0F3/PowerShell#11]
While executing the script I encouter the error message below:

"The system cannot find the file specified 
C:\xxxxx\temp\Server.cer"

I check in the temp folder and I have 3 files:
- xx.rsp
- tmp92A3.tmp
- tmp92A4.tmp

I think the issue is where the script is not renaming the temp file to Server.cer

Any help would be appreciated.

**Comment by J0F3** [comment]
Hi @prbreezy 

The .cer file should actually created automatically by certreq.exe which is invoked by the script to create and send the certificate request (line 318 and 326). So it is not a temp file which gets renamed, rather it is its own file which should be created. 

Can you please run the script again with `-Debug -Verbose` parameters to got more details what happens and provide me the output here? 

Also make sure that the CA does not require an approval before the certificate is issued because that is something that the script currently does not support.

Thanks!

**Comment by J0F3** [comment]
As I don not hear anything back since a while I assume you do no need further assistance.
So I am going to close that now.
